### ISSUE TITLE
Is this project stale? Would you be interested in sharing ownership for the NPM package?

### ISSUE THREAD

**Issue by simonhaenisch** [imcvampire/md-to-pdf#4]
Hi, I noticed that this project hasn't been updated in 2 years and was wondering whether it is stale?

I started a very similar project with the same name last year ([simonhaenisch/md-to-pdf](/simonhaenisch/md-to-pdf)), and lately I've been thinking about publishing it to NPM because more people started using it. However the name is taken by this package and NPM now has some rules to stop packages with similar names from being published, in order to increase collaboration I guess.

That's why I wanted to ask whether you'd be willing to transfer the ownership to me or to add me as an owner? My project has almost the same API (first argument is markdown file, second optionally the pdf output file). I can also change it so that invoking without arguments will convert all markdown files in the current folder, so that the behaviour doesn't break with the current one.

Anyway, I would also bump the major version number, indicating a breaking change, and the current version would still be available as `md-to-pdf@1.1.0` (or just `md-to-pdf@1`) for anyone who might currently be using it (there is no [dependents](https://www.npmjs.com/browse/depended/md-to-pdf)).

According to the [npm docs](https://docs.npmjs.com/cli/owner) it's as much as running

```
npm owner add simonhaenisch md-to-pdf
```

Thanks 🤓

**Comment by imcvampire** [comment]
Hi @simonhaenisch, 

There is no commit in 2 years ago because I create this project for my personal use and now, it serves me well.

But if you really want that name to publish a better package for the community, I'm happy to transfer it for you!

**Comment by simonhaenisch** [comment]
Thank you, that would be great ❤️

**Comment by imcvampire** [comment]
@simonhaenisch Added you as owner
